#!/usr/bin/env bash
# Install nginx and return a page that contains the string Hello World!
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
