#!/usr/bin/env bash
# Install nginx and print out the string "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
