#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.

for nums in {1..100}
do
    if (( nums % 3 == 0 && nums % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( nums % 3 == 0 ))
    then
        echo 'Fizz'
    elif (( nums % 5 == 0 )
    then
        echo 'Buzz'
    
    else
        echo "$nums"
    fi
done
