#!/usr/bin/env bash
# Bash script that gives you information about the "holbertonschool" file.
schfile=school
if [ -e "$schfile" ]
then
    echo "school file exists"

    if [ -s "$schfile" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$schfile" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
