#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user

chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo nginx -c 'service nginx restart'
